steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/grounded-datum-466612-u9/patient-fastapi/reminder-backend:latest', '.']
    dir: '.'

  # Test the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', 'us-central1-docker.pkg.dev/grounded-datum-466612-u9/patient-fastapi/reminder-backend:latest', 'python', '-c', 'import main; print("Application imported successfully")']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/grounded-datum-466612-u9/patient-fastapi/reminder-backend:latest']

  # Deploy to Cloud Run (optional, uncomment to enable)
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args: [
  #     'run', 'deploy', 'reminder-backend',
  #     '--image', 'us-central1-docker.pkg.dev/grounded-datum-466612-u9/patient-fastapi/reminder-backend:latest',
  #     '--region', 'us-central1',
  #     '--platform', 'managed',
  #     '--allow-unauthenticated',
  #     '--port', '8000'
  #   ]

# Configure timeout and machine type
timeout: '1200s'
options:
  machineType: 'E2_HIGHCPU_8'