name: Deploy to Cloud Run

env:
  SERVICE_NAME: reminder-backend
  PROJECT_ID: grounded-datum-466612-u9
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/grounded-datum-466612-u9/patient-fastapi/reminder-backend
  REGION: us-central1

on:
  push:
    branches:
      - back
  pull_request:
    branches:
      - back

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.PATIENT_BACK }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --service-account patient-back-deployment@grounded-datum-466612-u9.iam.gserviceaccount.com \
            --port 8000 \
            --timeout 180 \
            --quiet

      - name: Add IAM Policy Binding to Make Service Public
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --quiet